// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentasTecnoSoft;

namespace VentasTecnoSoft.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VentasTecnoSoft.Models.Cliente", b =>
                {
                    b.Property<int>("idCliente")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreCliente")
                        .HasColumnName("Nombre")
                        .HasMaxLength(20);

                    b.HasKey("idCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("VentasTecnoSoft.Models.PedidoProducto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantidad")
                        .HasColumnName("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("pedidoId")
                        .HasColumnName("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("productoId")
                        .HasColumnName("ProductoId")
                        .HasColumnType("int");

                    b.Property<float>("subTotal")
                        .HasColumnName("subTotal")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("pedidoId");

                    b.HasIndex("productoId");

                    b.ToTable("PedidoProducto");
                });

            modelBuilder.Entity("VentasTecnoSoft.Models.Pedidos", b =>
                {
                    b.Property<int>("idPedido")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("aprobado")
                        .HasColumnName("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("clienteId")
                        .HasColumnName("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("horaConfirmacion")
                        .HasColumnName("Hora Confirmacion")
                        .HasColumnType("Datetime");

                    b.HasKey("idPedido");

                    b.HasIndex("clienteId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("VentasTecnoSoft.Models.Producto", b =>
                {
                    b.Property<int>("idProducto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreProducto")
                        .HasColumnName("Nombre")
                        .HasMaxLength(20);

                    b.Property<int>("precio")
                        .HasColumnName("Precio")
                        .HasColumnType("int");

                    b.HasKey("idProducto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("VentasTecnoSoft.Models.TipoUsuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombreUsuario")
                        .HasMaxLength(20);

                    b.Property<bool>("tipoUsuario")
                        .HasColumnName("TipoUsuario")
                        .HasColumnType("bit");

                    b.HasKey("idUsuario");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("VentasTecnoSoft.Models.PedidoProducto", b =>
                {
                    b.HasOne("VentasTecnoSoft.Models.Pedidos", "pedido")
                        .WithMany("pedidoProducto")
                        .HasForeignKey("pedidoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("VentasTecnoSoft.Models.Producto", "producto")
                        .WithMany("pedidoProducto")
                        .HasForeignKey("productoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("VentasTecnoSoft.Models.Pedidos", b =>
                {
                    b.HasOne("VentasTecnoSoft.Models.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clienteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
